from ..palettes import psychopy as scheme

contrast_white = {
    "text": scheme['black'],
    "frame_bg": scheme['offwhite'] + 1,
    "docker_bg": scheme['yellow'],
    "docker_fg": scheme['black'],
    "panel_bg": scheme['offwhite'],
    "tab_bg": scheme['offwhite'] + 1,
    "bmpbutton_bg_hover": scheme['red'],
    "bmpbutton_fg_hover": scheme['offwhite'],
    "txtbutton_bg_hover": scheme['red'],
    "txtbutton_fg_hover": scheme['offwhite'],
    "rt_timegrid": scheme['black'],
    "rt_comp": scheme['blue'],
    "rt_comp_force": scheme['orange'],
    "rt_comp_disabled": [scheme['grey']],
    "rt_static": scheme['red'] * 75,
    "rt_static_disabled": scheme['grey'] * 75,
    "fl_routine_fg": scheme['offwhite'] + 1,
    "fl_routine_bg_slip": scheme['blue'],
    "fl_routine_bg_nonslip": scheme['green'],
    "fl_flowline_bg": scheme['black'],
    "fl_flowline_fg": scheme['offwhite'] + 1,
}