from ..palettes import psychopy as scheme

contrast_black = {
    "text": scheme['offwhite'],
    "frame_bg": scheme['black'],
    "docker_bg": "#800080",
    "docker_fg": scheme['offwhite'],
    "panel_bg": scheme['black'] + 1,
    "tab_bg": scheme['black'] + 1,
    "bmpbutton_bg_hover": [scheme['red']],
    "bmpbutton_fg_hover": scheme['offwhite'],
    "txtbutton_bg_hover": scheme['red'],
    "txtbutton_fg_hover": scheme['offwhite'],
    "rt_timegrid": scheme['offwhite'],
    "rt_comp": scheme['blue'],
    "rt_comp_force": scheme['orange'],
    "rt_comp_disabled": scheme['grey'],
    "rt_static": scheme['red'] * 75,
    "rt_static_disabled": scheme['grey'] * 75,
    "fl_routine_fg": scheme['white'],
    "fl_routine_bg_slip": scheme['blue'],
    "fl_routine_bg_nonslip": scheme['green'],
    "fl_flowline_bg": scheme['offwhite'],
    "fl_flowline_fg": scheme['black'],
}