name: psychopy
version: git
summary: 'PsychoPy - create experiments for behavioral science'
description: |
  PsychoPy is an open-source package for creating experiments in behavioral science.
  https://psychopy.org
grade: devel
confinement: devmode
base: core22

apps:
    psychopy:
        command: 'python3 -m psychopy'
        extensions: [gnome]
        plugs: [python, x11, pulseaudio, gsettings, home, network, network-control]

environment:
  PATH: $SNAP/usr/bin:$SNAP/bin:$SNAP/sbin:$PATH
  PYTHONPATH: $SNAP/lib/python3/site-packages:$PYTHONPATH
  LD_LIBRARY_PATH: $SNAP/usr/lib:$SNAP/lib:$SNAP/usr/lib/lib-arch:$SNAP/lib/lib-arch

parts:
  psychopy:
    plugin: python
    source: .
    python-packages:
      - pip
      - setuptools
      - wheel
      - attrdict
      - https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-22.04/wxPython-4.2.0-cp310-cp310-linux_x86_64.whl
      - wxasync
    stage-packages:
      - libssl-dev
      - libjpeg-dev
      - libtiff-dev
      - libsdl1.2-dev
      - libnotify-dev
      - freeglut3
      - ibus-gtk3
      - zlib1g
      - libsm6
      - libslang2
      - libsdl1.2debian
      - libgtk2.0-0
      - libpcre3
      - liblzma5