# upon any changes to the release branch, check that they can be safely merged back into the dev branch
# if this fails, try cherry picking conflicting commits into the dev branch then rerun
name: Check conflicts

on:
  workflow_dispatch:
    inputs:
        branch:
            description: 'Branch to test merge conflicts on'
            type: string
            required: true
  pull_request:
    branches: [ release ]

jobs:
  conflicts:
    name: Check that this branch can be merged into dev without conflicts
    runs-on: macos-11

    steps:
    - name: Checkout dev branch
      uses: actions/checkout@v4
      with:
        ref: dev
    
    - name: Try to merge (if triggered by a PR)
      if: github.head_ref
      run: |
        git merge --no-commit --no-ff ${{ github.head_ref }}
    
    - name: Try to merge (if triggered by a button)
      if: ${{ inputs.branch }}
      run: |
        git merge --no-commit --no-ff ${{ inputs.branch }}